import { Open_Sans } from "next/font/google";
import "./globals.css";
import Logo from "@/components/Logo/Logo";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "DocChat",
  description: "Generated by Ralph Sormillon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="container">
          <Logo />
          {children}
        </div>
      </body>
    </html>
  );
}
